### ISSUE TITLE
This library is breaking my imports.

### ISSUE THREAD

**Issue by conradogarciaberrotaran** [kuzxnia/asyns_factory_boy#3]
First, thanks for making this library!
But, I'm having a problem with it (and I'm guessing many will)
After installing, my imports broke:
```
ModuleNotFoundError: No module named 'tests.factories'
```
Apparently, there's a new "tests" module in site-packages
```
.pyenv/versions/3.10.10/.../lib/python3.10/site-packages/tests
```

that contains the tests for this lib. This means you're shipping everything in the repo, not just the library.
The setup.py should be configured correctly in order to fix this.

Thanks!

**Comment by kuzxnia** [comment]
thanks for your input, fixed in 1.0.1
